// <auto-generated />
using System;
using Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(FakeRubikStoreContext))]
    [Migration("20260405221432_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aplication.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("Aplication.Entities.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Codigo");

                    b.Property<int>("IdState")
                        .HasColumnType("integer")
                        .HasColumnName("IdEstado");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("IdUsuario");

                    b.HasKey("Id");

                    b.HasIndex("IdState");

                    b.HasIndex("IdUser");

                    b.ToTable("Envios", (string)null);
                });

            modelBuilder.Entity("Aplication.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp")
                        .HasColumnName("Fecha");

                    b.Property<double>("FinalPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("PrecioFinal");

                    b.Property<int>("IdDelivery")
                        .HasColumnType("integer")
                        .HasColumnName("IdEnvio");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("NumberCard")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numerotarjeta");

                    b.HasKey("Id");

                    b.HasIndex("IdDelivery");

                    b.HasIndex("IdUser");

                    b.ToTable("Ordenes", (string)null);
                });

            modelBuilder.Entity("Aplication.Entities.OrdersProducts", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("integer")
                        .HasColumnName("IdProducto");

                    b.Property<int>("IdOrder")
                        .HasColumnType("integer")
                        .HasColumnName("IdOrden");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("Precio");

                    b.Property<int>("ProductsNumber")
                        .HasColumnType("integer")
                        .HasColumnName("Cantidad");

                    b.HasKey("IdProduct", "IdOrder");

                    b.HasIndex("IdOrder");

                    b.ToTable("Productos_Ordenes", (string)null);
                });

            modelBuilder.Entity("Aplication.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Image")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("Imagen");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NombreProducto");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("Precio");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("Miniatura");

                    b.HasKey("Id");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("Aplication.Entities.ProductCategory", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("integer")
                        .HasColumnName("IdProducto");

                    b.Property<int>("IdCategory")
                        .HasColumnType("integer")
                        .HasColumnName("IdCategoria");

                    b.HasKey("IdProduct", "IdCategory");

                    b.HasIndex("IdCategory");

                    b.ToTable("Categorias_Productos", (string)null);
                });

            modelBuilder.Entity("Aplication.Entities.ProductsProviders", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<int>("IdProvider")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("IdProductosNavigationId")
                        .HasColumnType("integer");

                    b.Property<int>("IdProveedoresNavigationId")
                        .HasColumnType("integer");

                    b.HasKey("IdProduct", "IdProvider");

                    b.HasIndex("IdProductosNavigationId");

                    b.HasIndex("IdProveedoresNavigationId");

                    b.ToTable("ProductsProviders");
                });

            modelBuilder.Entity("Aplication.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("Aplication.Entities.Review", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("IdProducto");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<int>("Rate")
                        .HasColumnType("integer")
                        .HasColumnName("rate");

                    b.HasKey("ProductId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("Aplication.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdRol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("Aplication.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("Aplication.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdAddress")
                        .HasColumnType("integer")
                        .HasColumnName("IdDireccion");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer")
                        .HasColumnName("IdRol");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Contrasena");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Telefono");

                    b.Property<string>("SecondName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Apellido");

                    b.HasKey("Id");

                    b.HasIndex("IdAddress")
                        .IsUnique();

                    b.HasIndex("IdRole");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Aplication.Entities.UserDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Direccion");

                    b.Property<string>("City")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Country")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("pais");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("State")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("estado");

                    b.HasKey("Id");

                    b.ToTable("Direccion", (string)null);
                });

            modelBuilder.Entity("Aplication.Entities.Delivery", b =>
                {
                    b.HasOne("Aplication.Entities.State", "IdStateNav")
                        .WithMany("Deliveries")
                        .HasForeignKey("IdState")
                        .IsRequired()
                        .HasConstraintName("FK_Envios_Estado");

                    b.HasOne("Aplication.Entities.User", "IdUserNav")
                        .WithMany("Deliveries")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_Envios_Usuarios");

                    b.Navigation("IdStateNav");

                    b.Navigation("IdUserNav");
                });

            modelBuilder.Entity("Aplication.Entities.Order", b =>
                {
                    b.HasOne("Aplication.Entities.Delivery", "DeliveryInfo")
                        .WithMany("Orders")
                        .HasForeignKey("IdDelivery")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Envios");

                    b.HasOne("Aplication.Entities.User", "UserInfo")
                        .WithMany("Orders")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Usuarios");

                    b.Navigation("DeliveryInfo");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("Aplication.Entities.OrdersProducts", b =>
                {
                    b.HasOne("Aplication.Entities.Order", "OrderNav")
                        .WithMany("OrderProducts")
                        .HasForeignKey("IdOrder")
                        .IsRequired()
                        .HasConstraintName("FK_Productos_Ordenes_Ordenes");

                    b.HasOne("Aplication.Entities.Product", "ProductInfo")
                        .WithMany("OrderProducts")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Productos_Ordenes_Productos");

                    b.Navigation("OrderNav");

                    b.Navigation("ProductInfo");
                });

            modelBuilder.Entity("Aplication.Entities.ProductCategory", b =>
                {
                    b.HasOne("Aplication.Entities.Category", "CategoryNav")
                        .WithMany("ProductCategories")
                        .HasForeignKey("IdCategory")
                        .IsRequired()
                        .HasConstraintName("FK_Categorias_Productos_Categorias");

                    b.HasOne("Aplication.Entities.Product", "ProductNav")
                        .WithMany("ProductCategories")
                        .HasForeignKey("IdProduct")
                        .IsRequired()
                        .HasConstraintName("FK_Categorias_Productos_Productos");

                    b.Navigation("CategoryNav");

                    b.Navigation("ProductNav");
                });

            modelBuilder.Entity("Aplication.Entities.ProductsProviders", b =>
                {
                    b.HasOne("Aplication.Entities.Product", "IdProductosNavigation")
                        .WithMany("ProvidersProducts")
                        .HasForeignKey("IdProductosNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplication.Entities.Provider", "IdProveedoresNavigation")
                        .WithMany("ProvidersProducts")
                        .HasForeignKey("IdProveedoresNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdProductosNavigation");

                    b.Navigation("IdProveedoresNavigation");
                });

            modelBuilder.Entity("Aplication.Entities.Review", b =>
                {
                    b.HasOne("Aplication.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Review_Productos");

                    b.HasOne("Aplication.Entities.User", "Usuario")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Usuarios");

                    b.Navigation("Product");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Aplication.Entities.User", b =>
                {
                    b.HasOne("Aplication.Entities.UserDirection", "AdressInfo")
                        .WithOne("User")
                        .HasForeignKey("Aplication.Entities.User", "IdAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Direccion");

                    b.HasOne("Aplication.Entities.Role", "RoleNav")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Rol");

                    b.Navigation("AdressInfo");

                    b.Navigation("RoleNav");
                });

            modelBuilder.Entity("Aplication.Entities.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Aplication.Entities.Delivery", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Aplication.Entities.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Aplication.Entities.Product", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProvidersProducts");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Aplication.Entities.Provider", b =>
                {
                    b.Navigation("ProvidersProducts");
                });

            modelBuilder.Entity("Aplication.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Aplication.Entities.State", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("Aplication.Entities.User", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Aplication.Entities.UserDirection", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
